title: recordingbetter's devlog
description: Python, Django, DRF, Postgresql, AWS, Docker....
show_downloads: false
google_analytics: UA-68697418-2
theme: jekyll-theme-architect
rooturl: "http://recordingbetter.com"
baseurl: ""
categories_path : /categories.html

author:
  name: Joe Donghee Cho
  github: github.com/recordingbetter
  email: recordingbetter@gmail.com

permalink: /:categories/:year/:month/:day/:title

#category_list: [Python, Django, Gitbook, Git, AWS]

paginate_path: "/page:num/"
paginate: 10


gems: [jekyll-paginate-v2, jekyll-paginate, jekyll-feed]

