title: recordingbetter's blog
description: software develop log
show_downloads: false
google_analytics:
theme: jekyll-theme-architect

#site:
#  title: d;sfkjg;fdkgj

#github.repository_url: testgtttt