title: recordingbetter's devlog
description: Python, Django, DRF, Postgresql, AWS, Docker....
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
baseurl: "http://recordingbetter.com"
author:
  github: https://github.com/recordingbettrer


paginate_path: "/page:num/"
paginate: 12

gems: jekyll-paginate-v2, jekyll-paginate


